package com.myspace.loanfileanalysis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AppData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Returned Operations")
	private java.lang.Boolean returnedOperations;

	public AppData() {
	}

	public java.lang.Boolean getReturnedOperations() {
		return this.returnedOperations;
	}

	public void setReturnedOperations(java.lang.Boolean returnedOperations) {
		this.returnedOperations = returnedOperations;
	}

	public AppData(java.lang.Boolean returnedOperations) {
		this.returnedOperations = returnedOperations;
	}

}