package com.myspace.loanfileanalysis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Client Name")
	private java.lang.String clientName;
	@org.kie.api.definition.type.Label("Client ID")
	private java.lang.String clientID;

	@org.kie.api.definition.type.Label("Contact Information")
	private com.myspace.loanfileanalysis.ContactInformation contactInformation;

	@org.kie.api.definition.type.Label("Document Type")
	private String documentType;

	@org.kie.api.definition.type.Label(value = "Submission Date")
	private java.time.LocalDateTime submissionDate;

	@org.kie.api.definition.type.Label(value = "Comments/Notes")
	private java.lang.String comments;

	public Client() {
	}

	public java.lang.String getClientName() {
		return this.clientName;
	}

	public void setClientName(java.lang.String clientName) {
		this.clientName = clientName;
	}

	public java.lang.String getClientID() {
		return this.clientID;
	}

	public void setClientID(java.lang.String clientID) {
		this.clientID = clientID;
	}

	public com.myspace.loanfileanalysis.ContactInformation getContactInformation() {
		return this.contactInformation;
	}

	public void setContactInformation(
			com.myspace.loanfileanalysis.ContactInformation contactInformation) {
		this.contactInformation = contactInformation;
	}

	public java.lang.String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(java.lang.String documentType) {
		this.documentType = documentType;
	}

	public java.time.LocalDateTime getSubmissionDate() {
		return this.submissionDate;
	}

	public void setSubmissionDate(java.time.LocalDateTime submissionDate) {
		this.submissionDate = submissionDate;
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public Client(java.lang.String clientName, java.lang.String clientID,
			com.myspace.loanfileanalysis.ContactInformation contactInformation,
			java.lang.String documentType,
			java.time.LocalDateTime submissionDate, java.lang.String comments) {
		this.clientName = clientName;
		this.clientID = clientID;
		this.contactInformation = contactInformation;
		this.documentType = documentType;
		this.submissionDate = submissionDate;
		this.comments = comments;
	}

}