package com.myspace.loanfileanalysis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Client Name")
	private java.lang.String clientName;
	@org.kie.api.definition.type.Label("Client ID")
	private java.lang.String clientID;

	@org.kie.api.definition.type.Label(value = "Contact Information")
	private com.myspace.loanfileanalysis.ContactInformation contactInformation;

	@org.kie.api.definition.type.Label(value = "Document Type")
	private java.util.List<java.lang.String> documentType;

	public Client() {
	}

	public java.lang.String getClientName() {
		return this.clientName;
	}

	public void setClientName(java.lang.String clientName) {
		this.clientName = clientName;
	}

	public java.lang.String getClientID() {
		return this.clientID;
	}

	public void setClientID(java.lang.String clientID) {
		this.clientID = clientID;
	}

	public com.myspace.loanfileanalysis.ContactInformation getContactInformation() {
		return this.contactInformation;
	}

	public void setContactInformation(
			com.myspace.loanfileanalysis.ContactInformation contactInformation) {
		this.contactInformation = contactInformation;
	}

	public java.util.List<java.lang.String> getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(java.util.List<java.lang.String> documentType) {
		this.documentType = documentType;
	}

	public Client(java.lang.String clientName, java.lang.String clientID,
			com.myspace.loanfileanalysis.ContactInformation contactInformation,
			java.util.List<java.lang.String> documentType) {
		this.clientName = clientName;
		this.clientID = clientID;
		this.contactInformation = contactInformation;
		this.documentType = documentType;
	}

}