package com.myspace.loanfileanalysis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContactInformation implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ContactInformation() {
    }




}