package com.myspace.loanfileanalysis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FTCA implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "What is FATCA?")
	private java.lang.String whatisFATCA;
	@org.kie.api.definition.type.Label(value = "What is CRS?")
	private java.lang.String whatisCRS;
	@org.kie.api.definition.type.Label(value = "What is an Intergovernmental Agreement or IGA ?")
	private java.lang.String whatisanIntergovernmentalAgreementorIGA;
	@org.kie.api.definition.type.Label(value = "What is the purpose of FATCA/CRS ?")
	private java.lang.String whatsthepurposeofFATCA;
	@org.kie.api.definition.type.Label(value = "Are the FATCA & CRS agreements signed by India?")
	private java.lang.String aretheFATCACRSagreementssignedbyIndia;

	public FTCA() {
	}

	public java.lang.String getWhatisFATCA() {
		return this.whatisFATCA;
	}

	public void setWhatisFATCA(java.lang.String whatisFATCA) {
		this.whatisFATCA = whatisFATCA;
	}

	public java.lang.String getWhatisCRS() {
		return this.whatisCRS;
	}

	public void setWhatisCRS(java.lang.String whatisCRS) {
		this.whatisCRS = whatisCRS;
	}

	public java.lang.String getWhatisanIntergovernmentalAgreementorIGA() {
		return this.whatisanIntergovernmentalAgreementorIGA;
	}

	public void setWhatisanIntergovernmentalAgreementorIGA(
			java.lang.String whatisanIntergovernmentalAgreementorIGA) {
		this.whatisanIntergovernmentalAgreementorIGA = whatisanIntergovernmentalAgreementorIGA;
	}

	public java.lang.String getWhatsthepurposeofFATCA() {
		return this.whatsthepurposeofFATCA;
	}

	public void setWhatsthepurposeofFATCA(
			java.lang.String whatsthepurposeofFATCA) {
		this.whatsthepurposeofFATCA = whatsthepurposeofFATCA;
	}

	public java.lang.String getAretheFATCACRSagreementssignedbyIndia() {
		return this.aretheFATCACRSagreementssignedbyIndia;
	}

	public void setAretheFATCACRSagreementssignedbyIndia(
			java.lang.String aretheFATCACRSagreementssignedbyIndia) {
		this.aretheFATCACRSagreementssignedbyIndia = aretheFATCACRSagreementssignedbyIndia;
	}

	public FTCA(java.lang.String whatisFATCA, java.lang.String whatisCRS,
			java.lang.String whatisanIntergovernmentalAgreementorIGA,
			java.lang.String whatsthepurposeofFATCA,
			java.lang.String aretheFATCACRSagreementssignedbyIndia) {
		this.whatisFATCA = whatisFATCA;
		this.whatisCRS = whatisCRS;
		this.whatisanIntergovernmentalAgreementorIGA = whatisanIntergovernmentalAgreementorIGA;
		this.whatsthepurposeofFATCA = whatsthepurposeofFATCA;
		this.aretheFATCACRSagreementssignedbyIndia = aretheFATCACRSagreementssignedbyIndia;
	}

}