package com.myspace.loanfileanalysis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InitialStudyReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("submissionId")
	private java.lang.String submissionId;
	@org.kie.api.definition.type.Label("Reviewer Name")
	private java.lang.String reviewerName;
	@org.kie.api.definition.type.Label("Date Of Review")
	private java.time.LocalDate dateOfReview;
	@org.kie.api.definition.type.Label("Initial Findings")
	private java.lang.String initialFindings;
	@org.kie.api.definition.type.Label("recommendations")
	private java.lang.String recommendations;
	@org.kie.api.definition.type.Label("Required Additional Documents")
	private java.lang.String requiredAdditionalDocuments;
	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	public InitialStudyReport() {
	}

	public java.lang.String getSubmissionId() {
		return this.submissionId;
	}

	public void setSubmissionId(java.lang.String submissionId) {
		this.submissionId = submissionId;
	}

	public java.lang.String getReviewerName() {
		return this.reviewerName;
	}

	public void setReviewerName(java.lang.String reviewerName) {
		this.reviewerName = reviewerName;
	}

	public java.time.LocalDate getDateOfReview() {
		return this.dateOfReview;
	}

	public void setDateOfReview(java.time.LocalDate dateOfReview) {
		this.dateOfReview = dateOfReview;
	}

	public java.lang.String getInitialFindings() {
		return this.initialFindings;
	}

	public void setInitialFindings(java.lang.String initialFindings) {
		this.initialFindings = initialFindings;
	}

	public java.lang.String getRecommendations() {
		return this.recommendations;
	}

	public void setRecommendations(java.lang.String recommendations) {
		this.recommendations = recommendations;
	}

	public java.lang.String getRequiredAdditionalDocuments() {
		return this.requiredAdditionalDocuments;
	}

	public void setRequiredAdditionalDocuments(
			java.lang.String requiredAdditionalDocuments) {
		this.requiredAdditionalDocuments = requiredAdditionalDocuments;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public InitialStudyReport(java.lang.String submissionId,
			java.lang.String reviewerName, java.time.LocalDate dateOfReview,
			java.lang.String initialFindings, java.lang.String recommendations,
			java.lang.String requiredAdditionalDocuments,
			java.lang.String status) {
		this.submissionId = submissionId;
		this.reviewerName = reviewerName;
		this.dateOfReview = dateOfReview;
		this.initialFindings = initialFindings;
		this.recommendations = recommendations;
		this.requiredAdditionalDocuments = requiredAdditionalDocuments;
		this.status = status;
	}

}